### ISSUE TITLE
你好，我运行这块代码报错了，请问是怎么回事？

### ISSUE THREAD

**Issue by Silver0930** [LCAD-UFES/publications-tabelini-ijcnn-2019#3]
![微信截图_20200707114559](https://user-images.githubusercontent.com/22534574/86704808-d52e1700-c047-11ea-9cc9-bb042e547df4.png)

**Comment by lucastabelini** [comment]
Do the templates have an alpha channel? I had to remove the white background from the templates provided in the dataset to add the alpha channel.

**Comment by Silver0930** [comment]
Okey, when i changed the code in the method named get_mask_from_image , it goes well. So,am i right？or not ! ( the things what i do below)
![1594188996(1)](https://user-images.githubusercontent.com/22534574/86885230-78099280-c127-11ea-925b-56eddf98e53d.jpg)

**Comment by lucastabelini** [comment]
I cannot  understand what you're trying to say.
