### ISSUE TITLE
templates without alpha channel.

### ISSUE THREAD

**Issue by aiwithshekhar** [LCAD-UFES/publications-tabelini-ijcnn-2019#4]
Can you please answer my queries:-

1) I have GTSRB templates as jpg images, it does not have alpha channel. So i keep getting below errors i am unable to remove the white background.
![err](https://user-images.githubusercontent.com/31220538/130327899-dc7ee58b-5e31-42c6-bc76-1229aaa66e38.JPG)

2) [https://github.com/LCAD-UFES/publications-tabelini-ijcnn-2019/blob/master/generate_dataset.py#L333](url) When i run the code it runs infinitely because of these two while loops and break statement.

3) Also most of the time process_img function exit from below mentioned lines which causes no blending.
 [https://github.com/LCAD-UFES/publications-tabelini-ijcnn-2019/blob/3b826debedca54d97ddb5bcf2ecbe34d124b23b7/generate_dataset.py#L230](url) , [https://github.com/LCAD-UFES/publications-tabelini-ijcnn-2019/blob/3b826debedca54d97ddb5bcf2ecbe34d124b23b7/generate_dataset.py#L253](url), [https://github.com/LCAD-UFES/publications-tabelini-ijcnn-2019/blob/3b826debedca54d97ddb5bcf2ecbe34d124b23b7/generate_dataset.py#L256](url)

**Comment by lucastabelini** [comment]
1. You have to remove the white background. You can use tools for that or create a script that does that.
2. I'm not sure what might be causing that. It does not occur in my experiments.
3. Same as 2.

Are you using a custom dataset or the same ones that I used in the paper? If not, then there might be something incompatible with the code.

**Comment by aiwithshekhar** [comment]
Thanks for replying!
I am not using Coco dataset, I was using GTSRB images for background.

How have you decided on target_size=(1500, 1500). I am dealing with image of dimension (64,64) and template of dimension (44,44), for my dimension config what should be target_size?

**Comment by lucastabelini** [comment]
That target size was an arbitrary decision. Why are you using such small images? I can't see a case where you would need to run an object detector on such small images where the object occupies most of the space.

**Comment by aiwithshekhar** [comment]
Ya you are right! but i was checking if using this synthetic images for  VAE training can give good performance on Target dataset. 

I mostly think there will be domain gap, but just wanted to see for myself. What do you think?

**Comment by lucastabelini** [comment]
I'm not sure what you mean. Do you want to train a VAE for object detection?

**Comment by aiwithshekhar** [comment]
No , sorry for not being clear, training VAE for topk prediction for a given query image.

**Comment by lucastabelini** [comment]
So it's a classification task? I think it could work. I believe it has been shown to work in some papers.

**Comment by aiwithshekhar** [comment]
yeah i think i need to change the brightness more and add color jitter, to make it look like real images. Presently output looks like this.

![sd](https://user-images.githubusercontent.com/31220538/130366544-171015ab-8473-41ce-86fe-6c1e6addc8b7.JPG)
